version: '3.7'
services:
  # init redis
  redis:
    image: redis
    container_name: redis
    volumes:
      - redis:/var/lib/redis
    networks:
      - webnet
    env_file:
      - .env
    restart: always

  # init postgres_db
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - postgres:/var/lib/postgres
    networks:
      - webnet
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env

  # init pgadmin for database management
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - .env
    ports:
      - '5050:80'
    networks:
      - webnet

  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/app
      - ./nodemon.json:/app/nodemon.json
    container_name: reddit-server
    expose:
      - '3000'
    ports:
      - '3000:3000'
    env_file:
      - .env
    command: yarn dev
networks:
  webnet:

volumes:
  redis:
  postgres:
