version: '3.7'
services:
  # init redis
  redis:
    image: redis
    container_name: redis
    volumes:
      - redis:/var/lib/redis
    networks:
      - webnet
    restart: always

  # init postgres_db
  postgres_db:
    image: postgres
    container_name: postgres
    volumes:
      - postgres:/var/lib/postgres
    networks:
      - webnet
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=reddit
    ports:
      - 5432:5432

  # init pgadmin for database management
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=secret
    ports:
      - '5050:80'
    networks:
      - webnet

  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    depends_on:
      - redis
      - postgres_db
    volumes:
      - .:/app
      - ./nodemon.json:/app/nodemon.json
    container_name: reddit-server
    expose:
      - '3000'
    ports:
      - '3000:3000'
    environment:
      DB_HOST: postgres_db,
      REDIS_HOST: redis
    command: yarn dev
networks:
  webnet:

volumes:
  redis:
  postgres:
