version: '3.7'
services:
  # init redis
  redis:
    image: redis
    container_name: redis
    volumes:
      - redis:/var/lib/redis
    ports:
      - 6379:6379
    networks:
      - webnet
    restart: always

  # init postgres_db
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - postgres:/var/lib/postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=reddit
    networks:
      - webnet
    restart: always
    ports:
      - '5432:5432'

  # init pgadmin for database management
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.command
      - PGADMIN_DEFAULT_PASSWORD=secret
    ports:
      - '5050:80'
    networks:
      - webnet

  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    depends_on:
      - redis
      - postgres
    environment:
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=postgresql://postgres:postgres@postgres/reddit?schema=public
    volumes:
      - .:/app
      - ./nodemon.json:/app/nodemon.json
    container_name: reddit-server
    ports:
      - '3000:3000'
    expose:
      - '3000'
    command:
      [
        sh,
        -c,
        'cd prisma && rm -rf migrations && cd .. && npx prisma migrate dev --name init && npx prisma db seed && yarn dev',
      ]
    networks:
      - webnet

networks:
  webnet:

volumes:
  redis:
  postgres:
