version: '3.3'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=reddit
    ports:
      - 5432:5432
    logging:
      options:
        max-size: 10m
        max-file: '3'
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=secret
    ports:
      - '5050:80'
